#!/usr/bin/env bash
# installs nginx and configure my web server 227412-web-01 to listen on port 80
# returns  "Hello World" querying Nginx at its root 

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
