#!/usr/bin/env bash
# install load balance for web-01 and web-02

apt-get -y update
sudo apt-get install haproxy #install haproxy

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
frontend http80
  bind *:80
  timeout client 10s
  mode http
  default_backend allservers

backend allservers
   timeout connect 10s
   timeout server 20s
   mode http
   server 453-web-01 100.25.30.112:80 check
   server 453-web-02 54.237.113.234:80 check
"

chown haproxy:haproxy /etc/haproxy/haproxy.cfg
chmod 600 /etc/haproxy/haproxy.cfg

sudo service haproxy restart


