#!/usr/bin/env bash
# install load balance for web-01 and web-02

sudo apt-get -y update
sudo apt-get install -y haproxy

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get -y update

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
frontend http80
  bind *:80
  timeout client 10s
  mode http
  default_backend allservers

backend allservers
   timeout connect 10s
   timeout server 20s
   mode http
   server 453-web-01 100.25.30.112:80 check
   server 453-web-02 54.237.113.234:80 check
"

echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart

