#!/usr/bin/env bash
# 7-highlander
# this script Displays:
# "To infinity and beyond" indefinitely with a sleep 2 in between each iteration.
# Displaying "I am invincible!!!" when receiving a SIGTERM signal

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
