#!/usr/bin/env bash
# a script to display the time for 12 hours and 59 mintes:
# - display hours from 0 to 12
# - display minutes from 1 to 59

hour=0
minute=0

while (( hour <= 12 )); do
echo "Hour: $hour"

minute=1
while (( minute <= 59 )); do
echo "$minute"
((minute++))
done

((hour++))
donehour=0
minute=0

while (( hour <= 12 )); do
echo "Hour: $hour"

minute=1
while (( minute <= 59 )); do
echo "$minute"
((minute++))
done

((hour++))
done
