#!/usr/bin/env bash
# a scrip that displays:
# - content of the current directory
# - In a list format
# - Where only the part of the name after the first dash is displayed

for name in *
do
	echo "${name//[^-]*-/}"
done
