#!/usr/bin/env bash
# ssh config file

Host *
      PasswordAuthentication no
      IdentifyFile ~/.ssh/school
      sendEnv LANG LC_*
      HashKnownHosts yes
      GSSAPIAAuthentication yes
      GSSAPIDelegateCredentials no
